<?php

namespace TuCreusesOu\Enum;

enum Erreurs {
    case FORMULAIRE_NON_VALIDE;
    case CHAMP_MANQUANT;
    case MOT_DE_PASSE_DIFFERENT;
    case EMAIL_INVALIDE;
    case CARACTERES_INTERDITS_NOM;
    case MDP_INTERDIT;
    case CODE_EMAIL_MANQUANT;
    case CODE_EMAIL_DELAI_DEPASSE;
    case CODE_EMAIL_INCONNU;
    case CODE_EMAIL_GENERIQUE;
    case MAIL_DEJA_PRIS;
    case MDP_TROP_COURT;
    case INSCRIPTION_GENERIQUE;
    case EMAIL_INCONNU;
    case MAUVAIS_MDP;
    case IDENTIFIANT_AMI_INCONNU;
    case CHAMP_MDP_MANQUANT;
    case CARACTERES_INTERDITS_DESCRIPTION;
    case DESCRIPTION_TROP_LONGUE;
    case DATE_INVALIDE;
    case CDD_SANS_FIN;
    case DATE_FIN_PASSEE;
    case DEPARTEMENT_INCONNU;
}