version: "3.8"
services:
  php:
    build:
      dockerfile: php/Dockerfile
    volumes:
      - ..:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    links:
      - 'php'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../public:/var/www/html/public
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
volumes:
  mysqldata:
